shellEmulator: true

trustPolicy: no-downgrade

catalog:
  vite-plus: 0.2.3
  "@vitest/coverage-v8": 4.1.9
  "@arethetypeswrong/core": ^0.18.4
  publint: ^0.3.21
  typescript: ^6.0.3
  "@types/node": ^26.1.0
  automd: ^0.4.3
  changelogen: ^0.6.2
  knip: ^6.25.0

allowBuilds:
  "@parcel/watcher": true
  esbuild: true

minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.2.3"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.2.3"
  - "@voidzero-dev/vite-plus-darwin-x64@0.2.3"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.3"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.2.3"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.2.3"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.2.3"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.3"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.2.3"
  - vite-plus@0.2.3
